define(function(require) {
	'use strict';

	return [
		{
			'username': 'carldanley',
			'password': 'carldanley',
			'email': 'carl@bocoup.com',
			'openIdUrl': '',
			'firstName': 'Carl',
			'lastName': 'Danley',
			'nameSeenByOthers': 'Carl',
			'relationshipStatus': 'Single',
			'description': 'I like JS.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_USER', 'ROLE_ADMIN']
		},
		{
			'username': 'admin',
			'password': 'admin',
			'email': 'admin@admin.com',
			'openIdUrl': '',
			'firstName': 'Admin',
			'lastName': 'Admin',
			'nameSeenByOthers': 'Admin',
			'relationshipStatus': 'Single',
			'description': 'Pizza is good.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_ADMIN']
		},
		{
			'username': 'disabled',
			'password': 'disabled',
			'email': 'disabled@disabled.com',
			'openIdUrl': '',
			'firstName': 'Dis',
			'lastName': 'Abled',
			'nameSeenByOthers': 'Disabled',
			'relationshipStatus': 'Single',
			'description': 'I cannot login.',
			'sessionToken': '',
			'locked': false,
			'enabled': false,
			'expired': false,
			'authorities': ['ROLE_USER']
		},
		{
			'username': 'canonical',
			'password': 'canonical',
			'email': 'canonical@canonical.com',
			'openIdUrl': '',
			'firstName': 'Canon',
			'lastName': 'Ical',
			'nameSeenByOthers': 'Canonical',
			'relationshipStatus': 'Single',
			'description': 'Remember me?',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_ADMIN']
		},
		{
			'username': 'jmeas',
			'password': 'jmeas',
			'email': 'james@bocoup.com',
			'openIdUrl': '',
			'firstName': 'James',
			'lastName': 'Smith',
			'nameSeenByOthers': 'James',
			'relationshipStatus': 'Single',
			'description': 'I like JS.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_ADMIN', 'ROLE_USER']
		},
		{
			'username': 'jane.doe',
			'password': 'jane.doe',
			'email': 'jane.doe@gmail.com',
			'openIdUrl': '',
			'firstName': 'Jane',
			'lastName': 'Doe',
			'nameSeenByOthers': 'Jane',
			'relationshipStatus': 'Single',
			'description': 'Rave test user.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_USER']
		},
		{
			'username': 'john.doe',
			'password': 'john.doe',
			'email': 'john.doe@gmail.com',
			'openIdUrl': '',
			'firstName': 'John',
			'lastName': 'Doe',
			'nameSeenByOthers': 'John',
			'relationshipStatus': 'Single',
			'description': 'Rave test user.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_USER']
		},
		{
			'username': 'four.col',
			'password': 'four.col',
			'email': 'four.col@gmail.com',
			'openIdUrl': '',
			'firstName': 'Four',
			'lastName': 'Col',
			'nameSeenByOthers': 'Four',
			'relationshipStatus': 'Single',
			'description': 'Rave test user.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_USER']
		},
		{
			'username': 'fourwn.col',
			'password': 'fourwn.col',
			'email': 'fourwn.col@gmail.com',
			'openIdUrl': '',
			'firstName': 'Fourwn',
			'lastName': 'Col',
			'nameSeenByOthers': 'Fourwn',
			'relationshipStatus': 'Single',
			'description': 'Rave test user.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_USER']
		},
		{
			'username': 'threewn.col',
			'password': 'threewn.col',
			'email': 'threewn.col@gmail.com',
			'openIdUrl': '',
			'firstName': 'Threewn',
			'lastName': 'Col',
			'nameSeenByOthers': 'Threewn',
			'relationshipStatus': 'Single',
			'description': 'Rave test user.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_USER']
		},
		{
			'username': 'three.col',
			'password': 'three.col',
			'email': 'three.col@gmail.com',
			'openIdUrl': '',
			'firstName': 'Three',
			'lastName': 'Col',
			'nameSeenByOthers': 'Three',
			'relationshipStatus': 'Single',
			'description': 'Rave test user.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_USER']
		},
		{
			'username': 'twown.col',
			'password': 'twown.col',
			'email': 'twown.col@gmail.com',
			'openIdUrl': '',
			'firstName': 'Twown',
			'lastName': 'Col',
			'nameSeenByOthers': 'Twown',
			'relationshipStatus': 'Single',
			'description': 'Rave test user.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_USER']
		},
		{
			'username': 'george.doe',
			'password': 'george.doe',
			'email': 'george.doe@gmail.com',
			'openIdUrl': '',
			'firstName': 'George',
			'lastName': 'Doe',
			'nameSeenByOthers': 'George',
			'relationshipStatus': 'Single',
			'description': 'Rave test user.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_USER']
		},
		{
			'username': 'rave2011.myopenid.com',
			'password': '',
			'email': 'rave2011@myopenid.com',
			'openIdUrl': 'http://rave2011.myopenid.com/',
			'firstName': 'Rave',
			'lastName': '2011',
			'nameSeenByOthers': 'George',
			'relationshipStatus': 'Single',
			'description': 'Rave test user.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_USER']
		},
	];
});
