define(function(require) {
	'use strict';

	return [
		{
			'username': 'carldanley',
			'password': 'carldanley',
			'email': 'carl@bocoup.com',
			'openIdUrl': '',
			'firstName': 'Carl',
			'lastName': 'Danley',
			'nameSeenByOthers': 'Carl',
			'relationshipStatus': 'Single',
			'description': 'I like JS.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_USER', 'ROLE_ADMIN']
		},
		{
			'username': 'admin',
			'password': 'admin',
			'email': 'admin@admin.com',
			'openIdUrl': '',
			'firstName': 'Admin',
			'lastName': 'Admin',
			'nameSeenByOthers': 'Admin',
			'relationshipStatus': 'Single',
			'description': 'Pizza is good.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_ADMIN']
		},
		{
			'username': 'disabled',
			'password': 'disabled',
			'email': 'disabled@disabled.com',
			'openIdUrl': '',
			'firstName': 'Dis',
			'lastName': 'Abled',
			'nameSeenByOthers': 'Disabled',
			'relationshipStatus': 'Single',
			'description': 'I cannot login.',
			'sessionToken': '',
			'locked': false,
			'enabled': false,
			'expired': false,
			'authorities': ['ROLE_USER']
		},
		{
			'username': 'canonical',
			'password': 'canonical',
			'email': 'canonical@canonical.com',
			'openIdUrl': '',
			'firstName': 'Canon',
			'lastName': 'Ical',
			'nameSeenByOthers': 'Canonical',
			'relationshipStatus': 'Single',
			'description': 'Remember me?',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_ADMIN']
		},
		{
			'username': 'jmeas',
			'password': 'jmeas',
			'email': 'james@bocoup.com',
			'openIdUrl': '',
			'firstName': 'James',
			'lastName': 'Smith',
			'nameSeenByOthers': 'James',
			'relationshipStatus': 'Single',
			'description': 'I like JS.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_ADMIN', 'ROLE_USER']
		},
		{
			'username': 'jane.doe',
			'password': 'jane.doe',
			'email': 'jane.doe@gmail.com',
			'openIdUrl': '',
			'firstName': 'Jane',
			'lastName': 'Doe',
			'nameSeenByOthers': 'Jane',
			'relationshipStatus': 'Single',
			'description': 'Rave test user.',
			'sessionToken': '',
			'locked': false,
			'enabled': true,
			'expired': false,
			'authorities': ['ROLE_USER']
		},
	];
});
